daeng/src/components/visit/Calendar.jsx
daeng/src/components/visit/ScheduleTable.jsx
daeng/src/pages/visit/MyVisitList.jsx

- 내방문리스트에 진행 전인 일정은 취소 버튼 추가
- 당일 일정에서 시간이 지나면 취소버튼 없어짐

[Style/#33] 내방문리스트에 삭제버튼 추가

---

daeng/src/components/bookmark/BookMarkList.jsx
daeng/src/pages/Bookmark.jsx
daeng/src/stores/useFavoriteStore.js

- intersection observer를 사용해 무한스크롤 구현

[Feat/#51] 즐겨찾기 무한스크롤 구현

---

daeng/src/components/visit/VisitModal.jsx
daeng/src/pages/Error.jsx
daeng/src/pages/search/Search.jsx
daeng/src/pages/visit/PlaceVisitList.jsx
daeng/src/routes/AppRouter.jsx
daeng/src/services/axiosInstance.js
daeng/src/stores/useVisitStore.js
daeng/vite.config.js

- axiosInstance 자체에서 navigate가 안되는 버그를 수정했습니다.
- 에러페이지에서 뒤로가기가 작동안해서 주석처리해놨습니다
- 방문의사, 즐겨찾기, 장소검색은 axiosInstance로 변경했습니다.

:bug: Fix: 에러페이지 라우트 수정

---

daeng/src/components/user/UserRegister.jsx

- 쿠키에서 email, provider받아오게 수정했습니다!
- 서버에 올려서 확인해 봐야 합니당~~

[Feat/#50] 쿠키에서 email, provider 받기

---

daeng/src/components/Home/HomeDogPlaces.jsx
daeng/src/components/Home/HomeRecommendPlaces.jsx
daeng/src/components/Home/HomeTrendingPlaces.jsx

✨ Feat: 추천장소 이미지 연동

---

daeng/src/pages/search/Search.jsx

- 맵 로딩 전 홈에서 키워드 검색 시 화면 로딩안되는 오류 수정
- 일단 검색페이지로 이동만 되게 해놓음.

:bug: Fix: 홈에서 키워드 선택시 검색페이지로 이동

---

daeng/src/components/Home/HomeDogPlaces.jsx

[Feat/#65] 위도, 경도 property변경

---

daeng/src/components/user/LastContainer.jsx

- 로그아웃, 회원탈퇴시 로컬스토리지에 저장되어있던 userData 초기화 추가

[Feat/#42] 로그아웃, 회원탈퇴시 로컬스토리지 상태 초기화

---

daeng/src/components/Home/HomeDogPlaces.jsx
daeng/src/components/Home/HomeRecommendPlaces.jsx
daeng/src/components/Home/HomeSlider.jsx
daeng/src/components/Home/HomeTrendingPlaces.jsx
daeng/src/components/preference/PreferenceEdit.jsx
daeng/src/components/preference/PreferenceRegister.jsx
daeng/src/components/preference/TopSection.jsx
daeng/src/pages/Login.jsx
daeng/src/pages/search/PlaceDetail.jsx

[Style/#90] 전체 페이지 반응형 수정

---

daeng/src/components/bookmark/BookMarkList.jsx
daeng/src/components/commons/AreaBtn.jsx
daeng/src/components/commons/FilterBtn.jsx
daeng/src/components/detail/PlaceDescription.jsx
daeng/src/components/detail/PlaceInfo.jsx
daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/search/FilterBtnList.jsx
daeng/src/components/search/FilterModal.jsx
daeng/src/components/search/SearchBar.jsx
daeng/src/components/search/SearchPlaceList.jsx
daeng/src/components/visit/VisitModal.jsx
daeng/src/pages/Home.jsx
daeng/src/pages/search/PlaceDetail.jsx
daeng/src/stores/userStore.js
daeng/vite.config.js

[Feat/#44] 반응형 수정 및 이미지 추가

---

daeng/src/components/user/LastContainer.jsx

- 로그아웃, 회원탈퇴 시 메인페이지로 이동하도록 추가했습니다

[Feat/#42] 로그아웃, 회원탈퇴 시 메인페이지로 이동

---

daeng/src/components/alarm/AlarmDelete.jsx

[Feat/#73] 알림 취소 수정

---

daeng/src/components/alarm/AlarmButton.jsx

[Feat/#73] 알림 수정 

---

daeng/src/components/Home/HomeDogPlaces.jsx
daeng/src/components/Home/HomeLogout.jsx
daeng/src/components/Home/HomeRecommendPlaces.jsx
daeng/src/components/Home/HomeTrendingPlaces.jsx
daeng/src/components/Home/HomeWrapper.jsx

[Feat/#65] url, css 수정

---

daeng/src/components/Home/HomeKeywordPlaces.jsx
daeng/src/components/Home/HomeLogout.jsx
daeng/src/components/Home/HomeRecommendPlaces.jsx

[Feat/#65] css 수정

---

daeng/src/components/commons/ReviewKeywords.jsx
daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/pages/Home.jsx

- 상세페이지 폰트크기 수정
- 위치 비동의 알림 없앰

[Style/#88] 상세페이지 폰트크기 수정 및 위치비동의 알림 없앰

---

daeng/src/components/detail/PlaceInfo.jsx
daeng/src/components/search/SearchPlaceList.jsx

- 운영시간이 24:00:00 으로 뜨던걸 24:00으로 수정

[Style/#88] 검색페이지 endTime 수정

---

daeng/src/components/alarm/AlarmButton.jsx
daeng/src/components/alarm/AlarmDelete.jsx
daeng/src/components/pet/AddInputForm.jsx
daeng/src/components/pet/CommonStyle.jsx
daeng/src/components/pet/DeletePetData.jsx
daeng/src/components/pet/EditInputForm.jsx
daeng/src/components/pet/RegisterInputForm.jsx
daeng/src/components/review/ReviewForm.jsx
daeng/src/components/review/ReviewSlideshow.jsx
daeng/src/components/review/TotalReviewForm.jsx
daeng/src/components/review/WriteReview.jsx
daeng/src/components/user/LastContainer.jsx
daeng/src/components/user/PetContainer.jsx
daeng/src/components/user/UserContainer.jsx
daeng/src/components/user/UserRegister.jsx
daeng/src/pages/pet/AddPetPage.jsx
daeng/src/pages/pet/PetEditPage.jsx
daeng/src/pages/pet/PetRegisterPage.jsx
daeng/vite.config.js

- 
-
- 리뷰 작성하기가 안돼서 별점 테스트를 못했어요...ㅠㅠ

[Feat/#73] 버그 및 퍼블리싱 수정

---

daeng/src/components/user/LastContainer.jsx
daeng/src/components/user/UserEdit.jsx
daeng/src/components/user/UserRegister.jsx

[Feat/#65] Alert창 icon 수정

---

daeng/src/components/detail/PlaceInfo.jsx
daeng/src/components/search/SearchPlaceList.jsx
daeng/src/pages/Bookmark.jsx

- slice 로직 수정
- 즐겨찾기 첫 조회 useeffect추가

[Style/#88] 버그수정

---

daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/visit/VisitModal.jsx
daeng/src/pages/Bookmark.jsx

- 방문등록 안내사항 12px로 수정
- 장소 상세페이지 서브타이틀 15px로 수정

[style/#88] 폰트 크기 수정

---

daeng/src/components/Home/HomeSlider.jsx

- 배너 클릭 시 추후 업데이트 예정이라는 alert창 띄움

[Style/#88] 배너 클릭 시 안내창 추가

---

daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/review/ReviewForm.jsx
daeng/src/components/review/ReviewSlideshow.jsx
daeng/src/components/review/TotalReviewForm.jsx
daeng/src/components/review/WriteReview.jsx
daeng/src/pages/review/WriteReviewPage.jsx
daeng/vite.config.js

[Feat/#73] 전체적인 버그 수정 및 퍼블리싱 수정

---

daeng/src/components/detail/PlaceTitle.jsx
daeng/src/services/axiosInstance.js
daeng/src/stores/useFavoriteStore.js
daeng/src/stores/useVisitStore.js

- 401에러 로그인페이지로 리다이렉트 추가
- 비로그인 유저 방문등록 막음

[Style/#88] 1차 마지막 수정..

---

daeng/src/components/Home/HomeHeader.jsx
daeng/src/components/commons/Sorting.jsx
daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/review/AIReview.jsx
daeng/src/components/review/ReviewForm.jsx
daeng/src/components/review/ReviewSlideshow.jsx
daeng/src/components/review/ReviewSorting.jsx
daeng/src/components/review/TotalReviewForm.jsx
daeng/src/components/review/WriteReview.jsx
daeng/src/components/user/RoutePage.jsx
daeng/src/firebase/firebase.js
daeng/src/firebase/firebaseMessaging.js
daeng/src/pages/review/WriteReviewPage.jsx
daeng/vite.config.js

[Feat/#73] 버그 및 알림 수정

---

daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/review/TotalReviewForm.jsx

- 리뷰 전체 보기에서 arrow 클릭하면 해당 장소 상세보기로 가는 라우트 추가했습니다!

[Feat] 리뷰 전체보기 페이지에서 장소 상세보기 라우트 설정

---

daeng/index.html
daeng/src/routes/AppRouter.jsx

- 네이버 애널리틱스 추가
- env 파일에 네이버 추적 ID 환경변수 추가해야합니다

[Feat/#147] 애널리틱스 추가

---

daeng/src/pages/Error.jsx

- 파라미터로 DELETE_USER이 날라오면 탈퇴회원 에러페이지 띄움

[Style/#77] 탈퇴 회원 에러페이지 추가

---

daeng/src/components/map/Map.jsx
daeng/src/pages/Home.jsx
daeng/src/stores/useLocationStore.js
daeng/vite.config.js

- position 받아올 때 accuracy 추가해 정확도가 더 높은 위치 측정될 시 현재 위치 변경
- accuracy는 실제 위치와의 거리차이(m)를 나타냄, 즉 낮을 수록 정확도가 높음

[Feat/#44] 실시간 위치 정확도 개선

---

daeng/src/components/Home/HomeStory.jsx
daeng/src/components/story/OtherUserStory.jsx
daeng/src/components/story/ShowMyStory.jsx

[Feat/#191] 유저별 스토리 상세목록 조회 API 연동 완료

---

daeng/src/components/story/DeleteStory.jsx
daeng/src/components/story/ShowMyStory.jsx
daeng/src/components/story/UploadVideo.jsx

- 스토리 삭제 API 연동 완료 했고 버그도 수정했습니다!

[Feat/#189] 스토리 삭제 API 연동 및 버그 수정

---

daeng/src/components/Home/HomeStory.jsx
daeng/src/components/story/Detail.jsx
daeng/src/components/story/OtherUserStory.jsx
daeng/src/components/story/ShowMyStory.jsx
daeng/src/components/story/StoryCommonStyle.jsx
daeng/src/components/story/UploadVideo.jsx

[Feat/#189] 스토리 퍼블리싱 최종 수정

---

daeng/src/components/Home/HomeStory.jsx
daeng/src/components/story/ShowMyStory.jsx

- 로그인하지 않은 유저에게 로그인 필요 알림 표시(401)
- 404 에러 메시지를 상황별로 구분하여 Alert 처리
- 기타 에러 상황에 대한 기본 처리 로직 유지

[Feat] 스토리 - 로그인 상태 및 에러 메시지 분기 처리 추가

---

daeng/src/components/Home/HomeStory.jsx
daeng/src/components/story/OtherUserStory.jsx

- 유저 스토리 확인 후 테두리 색 변경
- 유저 스토리 확인 후 맨 뒤로 이동

[Feat/#191] 유저 스토리 확인 API 연동

---

daeng/src/components/Home/HomeHeader.jsx
daeng/src/components/commons/SweetAlert.jsx
daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/map/Map.jsx
daeng/src/components/review/DeleteReview.jsx
daeng/src/components/review/ReviewForm.jsx
daeng/src/components/user/LastContainer.jsx
daeng/src/pages/search/PlaceDetail.jsx
daeng/src/services/axiosInstance.js
daeng/src/stores/useFavoriteStore.js
daeng/src/stores/useVisitStore.js

- 알림창 수정
- 지도에서 마커 클릭 시 상세페이지로 이동
- 로딩 추가
- 내가 쓴 리뷰에서 리뷰타입 구분, 삭제 알림창 문구 수정
- 퍼블리싱 수정
- 이거 올리고 중복코드 있으면 수정하겠습니닷

[bug/#207]  피드백 수정

---

daeng/src/components/story/OtherUserStory.jsx

[Feat/#189] 상태바 추가

---

daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/pet/AddInputForm.jsx
daeng/src/components/pet/DeletePetData.jsx
daeng/src/components/pet/EditInputForm.jsx
daeng/src/components/pet/RegisterInputForm.jsx
daeng/src/components/review/DeleteReview.jsx
daeng/src/components/review/ReviewForm.jsx
daeng/src/components/review/TotalReviewForm.jsx
daeng/src/components/review/WriteReview.jsx
daeng/src/components/story/StoryCommonStyle.jsx
daeng/src/pages/review/MyReviewPage.jsx

- 펫 CRUD랑 리뷰 부분에 spinner 추가
- 리뷰 글자수 제한 색상 검정으로 수정 
- 리뷰 전체보기 반응형 keyword 부분 피그마랑 똑같이 수정

[Bug/#210] 2차 배포전 퍼블리싱 수정 & spinner 추가 

---

daeng/index.html
daeng/src/components/commons/SquareBtn.jsx
daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/hopscotch/HopscotchMap.jsx
daeng/src/components/hopscotch/ProgressBar.jsx
daeng/src/components/map/Map.jsx
daeng/src/components/visit/VisitModal.jsx
daeng/src/pages/Bookmark.jsx
daeng/src/pages/Hopscotch.jsx
daeng/src/pages/search/Search.jsx

- 방문등록모달 z-index 푸터보다 낮춤
- 방문등록, 실시간 리뷰 placeId 잘못 전달한 것 수정
- 맵 버벅거림 및 센터이동 수정(구글폼 피드백)
- 땅따먹기 애니메이션 수정
- 모바일에서 자동확대 안되게 함
- 모바일기준 퍼블리싱 수정

[Bug/#207]

---

daeng/src/components/bookmark/BookMarkList.jsx
daeng/src/components/commons/FavoriteList.jsx
daeng/src/components/commons/Sorting.jsx
daeng/src/components/detail/PlaceDescription.jsx
daeng/src/components/detail/PlaceInfo.jsx
daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/hopscotch/HopscotchMap.jsx
daeng/src/components/hopscotch/LandOwnerProfile.jsx
daeng/src/components/hopscotch/MyLandLabel.jsx
daeng/src/components/hopscotch/ProgressBar.jsx
daeng/src/components/map/Map.jsx
daeng/src/components/search/FilterBtnList.jsx
daeng/src/components/visit/Calendar.jsx
daeng/src/components/visit/ScheduleTable.jsx
daeng/src/components/visit/VisitDateSection.jsx
daeng/src/components/visit/VisitScheduleList.jsx
daeng/src/components/visit/VisitTimePets.jsx
daeng/src/pages/Bookmark.jsx
daeng/src/pages/Hopscotch.jsx
daeng/src/pages/search/PlaceDetail.jsx
daeng/src/pages/visit/MyVisitList.jsx
daeng/src/pages/visit/PlaceVisitList.jsx

- 검색 필터버튼 중복코드 수정
- 방문등록취소 alert text 수정
- 맡은 페이지 styled-component 위치 변경

[Bug/#207] 코드 리팩토링

---

daeng/src/components/Home/HomeStory.jsx
daeng/src/components/story/OtherUserStory.jsx

[Bug/#207] 다른 스토리 보고 전체 새로고침 되는 거 수정

---

daeng/src/components/detail/PlaceReviewList.jsx
daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/story/Detail.jsx

- 땅주인 아닐 시 story 업로드 못한다는 alert띄움

[Bug/#207] 스토리 alert수정

---

daeng/public/firebase-messaging-sw.js
daeng/src/firebase/firebaseMessaging.js

- 땅주인 알림 포그라운드/백그라운드 에서 오는 거 확인 후, 새 땅주인 알림 클릭 시 땅따먹기 페이지로 리다이렉트

[Bug/#207] 땅주인 알림 수정

---

daeng/src/components/search/SearchBar.jsx

- 검색어 자동 완성 추가
- 검색결과가 지금은 좀 부정확할 수도 있습니다. 백에서 코드 수정 조금 해야한다고 합니다

:sparkles: Feat: 검색어 자동완성 추가

---

daeng/public/firebase-messaging-sw.js
daeng/src/firebase/firebaseMessaging.js
daeng/vite.config.js

[Bug/#210] 알림수정 

---

daeng/src/components/bookmark/BookMarkList.jsx
daeng/src/pages/Bookmark.jsx

- 즐겨찾기 alert 오타 수정
- 필요없는 코드 삭제

:bug: Fix: 즐겨찾기 alert 오타 수정

---

daeng/public/firebase-messaging-sw.js

- 알림 백그라운드에서 오류나는 부분 수정
- notification에서 payload.data로 수정했습니다 
- 
-

[Bug/#210] 알림 버그 수정

---

daeng/package-lock.json
daeng/package.json
daeng/src/components/commons/UploadStoryBtn.jsx
daeng/src/components/hopscotch/HopscotchMap.jsx
daeng/src/components/visit/VisitModal.jsx

:bug: Fix: 시군구 경계면 데이터 압축 해제 및 로그 추가

---

daeng/src/components/hopscotch/HopscotchMap.jsx

:art: Refactor: 땅따먹기 로딩 추가

---

daeng/src/components/hopscotch/HopscotchMap.jsx

:fire: Delete: 땅따먹기 로딩 삭제

---

daeng/src/components/Home/HomeStory.jsx

🐛 Fix: 스토리 개수 확인 코드수정

---

daeng/src/components/review/WriteReview.jsx
daeng/src/firebase/firebaseMessaging.js

[Bug/#210] 리뷰 등록 문구 수정 

---

daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/search/SearchPlaceList.jsx
daeng/src/pages/Hopscotch.jsx
daeng/src/services/axiosInstance.js

- 즐겨찾기 토글 무조건 되는 것 수정
- 땅따먹기 401에러 시 처리

[Bug/#207] 즐겨찾기 토글 수정

---

daeng/src/firebase/firebaseMessaging.js

[bug/#210] 코드 복구

---

daeng/src/components/detail/PlaceTitle.jsx
daeng/src/components/search/SearchPlaceList.jsx

[Bug/#207] 즐찾 토글 성공시에만 수정

---

daeng/public/firebase-messaging-sw.js
daeng/src/components/admin/AdminImgUpload.jsx
daeng/src/components/admin/GeoLocationField.jsx
daeng/src/components/commons/BookMarker.jsx
daeng/src/components/commons/Confetti.jsx
daeng/src/components/review/MyReviewList.jsx
daeng/src/components/review/TotalReviewForm.jsx
daeng/src/components/review/WriteReview.jsx
daeng/src/firebase/firebaseMessaging.js
daeng/src/pages/alarm/AlarmPage.jsx
daeng/src/stories/ConfirmBtn.stories.jsx

[Bug/#210] 주석&로그 삭제 

---

daeng/src/components/review/WriteReview.jsx
daeng/vite.config.js

- handleRemoveImage함수 추가했습니다
- 리뷰 등록 후에 페이지(전체보기)로 넘어갈 때 로딩 추가했습니다 
- 리뷰 하루에 하나만 작성 가능한 거 확인했습니다
- 
-

[Bug]handleRemoveImage함수 추가

---

daeng/src/components/guide/SliderCommonStyle.jsx
daeng/vite.config.js

[Bug/#210] banner arrow z-index 수정 

---

daeng/src/components/detail/PlaceDescription.jsx

- 백에서 넘겨줄 때 <br>이 있을때마다 줄바꿈하고 위아래 줄간격 수정했습니다

:lipstick: Style: 시설 소개 줄바꿈 추가

---

daeng/src/components/detail/PlaceDescription.jsx

- undefined일 때 replace가 작동안해서 오류나는 것 수정

:bug: Fix: 시설소개 undefined일때 빈 값 추가

---

README.md
daeng/src/components/commons/ConfirmBtn.jsx
daeng/src/pages/Login.jsx
daeng/src/services/axiosInstance.js
daeng/src/stories/ConfirmBtn.stories.jsx
daeng/src/stories/LandOwnerProfile.stories.jsx
daeng/vercel.json

- 확인버튼 컴포넌트에 isLoading 변수를 추가해서 isLoading이 true면 사진처럼 로딩스피너가 돌아가는 버튼으로 나오게 만들었습니다 
- 필요하면 쓰세요잉~

Feat/#282 확인버튼에 로딩스피너 추가

---

daeng/index.html
daeng/src/components/commons/FilterBtn.jsx
daeng/src/components/commons/Footer.jsx
daeng/src/components/commons/ScrollBtn.jsx
daeng/src/components/map/Map.jsx
daeng/src/components/search/FilterModal.jsx
daeng/src/components/search/SearchPlaceList.jsx
daeng/src/main.jsx

- index.html과 main.jsx에서 네이버애널리틱스, 구글광고 스크립트를 주석처리해 서드파티쿠키를 없앰
- 푸터, 스크롤업버튼, 필터버튼 등 prop이 dom에 전달되는 것 때문에 발생하던 콘솔 에러 해결
⬇️
아마 배포에 올리면 성능쪽도 90넘을 것 같네요 홀홀

Feat/#282 검색페이지 최적화

---

daeng/src/components/bookmark/BookMarkList.jsx
daeng/src/components/commons/ConfirmBtn.jsx
daeng/src/components/commons/DeleteBtn.jsx
daeng/src/components/commons/FavoriteList.jsx
daeng/src/components/commons/ReviewKeywords.jsx
daeng/src/components/visit/Calendar.jsx
daeng/src/components/visit/VisitModal.jsx
daeng/src/components/visit/VisitTimePets.jsx
daeng/src/pages/Error.jsx
daeng/src/style/font.css

- 방문 등록 버튼 로딩 스피너 변경
- 콘솔 에러들 해결
- 폰트 깨짐 수정
⬇️
⬇️

Feat/#282 즐겨찾기, 방문관련, 에러 페이지 리팩토링

---

daeng/src/components/commons/SelectLabel.jsx
daeng/src/components/pet/AddInputForm.jsx
daeng/src/components/pet/EditInputForm.jsx
daeng/src/components/pet/RegisterInputForm.jsx
daeng/src/components/user/mypage/PetContainer.jsx
daeng/src/components/user/mypage/RoutePage.jsx

- 펫 등록, 추가, 수정 라이트하우스 측정 점수 향상
- `SelectLabel`에 `htmlFor`을 삽입해주었습니다(주로 select & 라벨 연결이 안되어 있어서 접근성이 낮았습니다😮‍💨)
- 로컬에서 측정한 라이트하우스 점수는 수정 후에 캡쳐 했고 배포서버에서 캡처한 이미지는 변경한 코드 합치기 전입니다
**pet 등록**
- 로컬
- 배포 서버 
**pet 추가**
- 로컬
- 배포 서버 
**pet 수정**
- 로컬 
- 배포 서버 
- **마이페이지** 배포 서버랑 합친 후 라이트하우스 측정 결과입니다🥳

[Feat/#284] 펫 CRUD 최적화

---

daeng/src/components/review/MyReviewList.jsx
daeng/src/components/review/TotalReviewForm.jsx
daeng/src/components/review/total/TotalReviewStyle.jsx
daeng/src/style/font.css

리뷰 등록 페이지랑 전체 보기 페이지 최적화 진행했습니다
- `배포 서버 : 리뷰등록`
- `로컬 : 리뷰등록`
- `배포 서버 : 리뷰 전체보기`
- `로컬 : 리뷰 전체보기`
- 위에 첨부 했습니다
`펫 등록`이랑 `펫 수정`페이지 최적화 결과 입니다

[Feat/#284] 리뷰 등록 페이지 & 리뷰 전체 보기 페이지 최적화

---

daeng/src/pages/alarm/AlarmPage.jsx

[Feat/#284] 알림페이지 최적화
